### ISSUE TITLE
Typo in language name?

### ISSUE THREAD

**Issue by seanPhill** [symbol/handbook#10]
At one point "Bahasa Indonesia" (Indonesian language) was suddenly changed to "Bahasaonesia", (effectively onesian language, whatever that might be) ;) and carried forward ever since. 
Is this intentional in order to fit some sort of space constraint? It looks like a weird choice.

Why not just use the word "Indonesia"?

**Comment by segfaultxavi** [comment]
Apologies, I broke it inadvertently. It should be fixed now.

Would "Indonesia" work equally well or would it be confused with the country? There are no length constrains.

**Comment by seanPhill** [comment]
If the list is comfortable with the full "Bahasa Indonesia" that is perfect. (If constrained for space, I would prefer "Indonesia", and could not imagine any confusion in a list that is solely for languages.)

**Comment by segfaultxavi** [comment]
Cool, I'll leave it as "Bahasa Indonesia". Thanks for reporting!
