### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by jabo38** [symbol/handbook#11]
there should be no space after "Symbol" 
![image](https://user-images.githubusercontent.com/10395907/128049941-750b69ff-217f-4518-9455-c7f12d2d34d7.png)

**Comment by segfaultxavi** [comment]
It's not there anymore :)

**Comment by jabo38** [comment]
fastest issue closed!

**Comment by segfaultxavi** [comment]
To be honest, it was already fixed, I don't know where did you get your screenshots from :D
